language: node_js
node_js:
  - "12.18.3"

# S: Build Lifecycle
install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "zeqinjie"
  - git config user.email "187519328@qq.com"
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  # Coding Pages
  - git push --force --quiet "https://dfz:${CO_TOKEN}@${CO_REF}" master:master
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages --tags
  # Coding Pages
  - git push --quiet "https://dfz:${CO_TOKEN}@${CO_REF}" master:master --tags


branches:
  only:
    - master

env:
  global:
   - GH_REF: github.com/zeqinjie/zeqinjie.github.io.git